+SELECT TOP (1000) [HistoryId]
      ,[BusinessEntityTypeId]
      ,[LocationTypeId]
      ,[PunitId]
      ,[TripDate]
      ,[TripNumber]
      ,[OriginTerminalList]
      ,[DestinationTerminalList]
      ,[Type]
      ,[Description]
      ,[PayRate]
      ,[MilesDays]
      ,[PaidMiles]
      ,[TotalAmount]
      ,[Extended]
      ,[FedExType]
      ,[PersonId]
      ,[PayPeriodEnding]
      ,[PayrollNotes]
      ,[FedExId2]
      ,[PersonId2]
      ,[FedExId]
      ,[LastUpdate]
  FROM [RedBone].[dispatch].[PR_SettlementStmt_History]
