INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (1,'OTR' ,'OTR' ,1)
INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (2,'FedEx' ,'FedEx' ,1)
INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (3,'Salary' ,'Salary' ,1)
INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (4,'Hourly' ,'Hourly' ,1)
INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (5,'Unassigned' ,'Unassigned' ,1)
INSERT INTO [payroll].[PayrollOTRPersonLeaveType] ([PayrollOTRPersonLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (6,'N/A' ,'N/A' ,1)
