INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (0,'Unassigned' ,'Unassigned' ,1)
INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (1,'None' ,'None' ,1)
INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (2,'OTR' ,'OTR' ,1)
INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (3,'FedEx' ,'FedEx' ,1)
INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (4,'Salary' ,'Salary' ,1)
INSERT INTO [payroll].[PayrollOTRLeaveType] ([PayrollOTRLeaveTypeId] ,[Type], [Description], [Enabled]) VALUES (5,'Hourly' ,'Hourly' ,1)
